CREATE OR REPLACE FUNCTION GET_DESCRIPTION
(p_ID IN SEGMERCADO.ID%type)
    RETURN SEGMERCADO.DESCRICAO%type
IS
    v_DESCRIPTION SEGMERCADO.DESCRICAO%type;
BEGIN
    SELECT DESCRICAO INTO v_DESCRIPTION FROM SEGMERCADO WHERE ID = p_ID;
    RETURN v_DESCRIPTION;
END;