SET SERVEROUTPUT ON;

DECLARE
    v_ID SEGMERCADO.ID%type := 1;
    v_DESCRIPTION SEGMERCADO.DESCRICAO%type;
BEGIN
    SELECT DESCRICAO INTO v_DESCRIPTION FROM SEGMERCADO WHERE ID = v_ID;
    dbms_output.put_line(v_DESCRIPTION);
END;