DECLARE
    v_ID SEGMERCADO.ID%type =: 1;
    v_DESCRIPTION SEGMERCADO.DESCRICAO%type := 'Varejo';
BEGIN
    INSERT INTO SEGMERCADO(ID, DESCRIPTON) VALUES (v_ID, upper(v_DESCRIPTION));
    COMMIT;
END;