DECLARE
    v_FATURAMENTO_PREVISTO CLIENTE.v_FATURAMENTO_PREVISTO%type := 12000;
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
    IF v_FATURAMENTO_PREVISTO < 10000 THEN
        v_CATEGORIA := "PEQUENO";

    ELSIF v_FATURAMENTO_PREVISTO < 50000 THEN
        v_CATEGORIA := "MÉDIO";

    ELSIF v_FATURAMENTO_PREVISTO < 100000 THEN
        v_CATEGORIA := "MÉDIO GRANDE";

    ELSE v_FATURAMENTO_PREVISTO < 50000 THEN
        v_CATEGORIA := "GRANDE";
    END IF;
END;