DECLARE
    v_ID SEGMERCADO.ID%type := 1;
    v_DESCRIPTION SEGMERCADO.DESCRICAO%type := 'Varejo';
BEGIN
    INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (v_ID, upper(v_DESCRIPTION));
    
    v_ID := 2;
    v_DESCRIPTION := 'Atacado';
    INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (v_ID, upper(v_DESCRIPTION));

    v_ID := 3;
    v_DESCRIPTION := 'Esportista';
    INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (v_ID, upper(v_DESCRIPTION));
    
    COMMIT;
END;